#!/usr/bin/env python3
"""Build the table that annotates candidates with their complete code.

The text service reads this file directly and writes each candidate's own
code into the candidate window. It cannot reuse the runtime `hengma`
dictionary for that: `hengma` imports the typo-tolerant `hengma_fuzzy`, so a
lookup there returns every fuzzy variant of a code as well (`ing`, `qig`,
`qnig`, ... for 清). This tool reads only the single-character table and keeps
the complete code for each reading:

    清  qing / qingz / qingzs  ->  qingzs
    应  ying / yingb / yingbg  ->  yingbg

Output is deterministic: characters are emitted in the order they first
appear in the source table.
"""

from __future__ import annotations

import argparse
import io
import pathlib
import sys

HEADER = """# Rime dictionary
# encoding: utf-8
# Generated by data-tools/generate_codes.py - do not edit by hand.
#
# Candidate annotation table: the complete Hengma code(s) per character.
---
name: hengma_char_codes
version: "{version}"
sort: original
...
"""


def read_entries(path: pathlib.Path):
    """Yield (text, code) pairs from a Rime dictionary file."""
    started = False
    with io.open(path, encoding="utf-8") as handle:
        for line in handle:
            if not started:
                if line.startswith("..."):
                    started = True
                continue
            line = line.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) >= 2 and parts[0] and parts[1]:
                yield parts[0], parts[1]


def maximal_codes(codes: set[str]) -> list[str]:
    """Drop every code that is only a prefix of another code.

    A character's codes grow by refinement (`qing` -> `qingz` -> `qingzs`), so
    the prefixes are partial codes, not answers. What survives is one complete
    code per reading: 清 keeps `qingzs` alone, while a character with two
    readings such as 吖 keeps both `azk` and `yazk` rather than silently
    picking the longer reading.
    """
    return sorted(
        code for code in codes
        if not any(other != code and other.startswith(code) for other in codes)
    )


def build(source: pathlib.Path, version: str):
    codes: dict[str, set[str]] = {}
    order: list[str] = []
    for text, code in read_entries(source):
        if text not in codes:
            order.append(text)
            codes[text] = set()
        codes[text].add(code)

    lines = [HEADER.format(version=version)]
    rows = 0
    for text in order:
        for code in maximal_codes(codes[text]):
            lines.append(f"{text}\t{code}\n")
            rows += 1
    return "".join(lines), rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default="data/hengma.dict.yaml",
                        type=pathlib.Path)
    parser.add_argument("--output", default="data/hengma_char_codes.dict.yaml",
                        type=pathlib.Path)
    parser.add_argument("--version", default="0.3.0")
    args = parser.parse_args()

    if not args.source.exists():
        print(f"missing source table: {args.source}", file=sys.stderr)
        return 1

    content, count = build(args.source, args.version)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with io.open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    print(f"{args.output}: {count} characters")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
